---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-4"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- config/
- dist/
- node_modules/
- tests/
- fastboot-tests/
- vendor/
- tmp/
